name: Staging Deployment

on:
  workflow_dispatch:

jobs:

  staging:
    name: Staging
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: 🔔 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: 💻 Install Dependencies
        run: npm ci

      - name: 📜 Create Env File
        run: |
          cp .env.example .env

      - name: 🔨 Build
        run: npm run build --if-present

      - name: 🚀 SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # Server IP or domain
          server: ${{ secrets.SERVER_HOST }}
          # Server username
          username: ${{ secrets.SERVER_USERNAME }}
          # Port
          port: ${{ secrets.SERVER_PORT }}
          # Server's private key
          ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          # Source to take files from, will take all files under this path. Default is ./*
          local_path: ./dist/*
          # Destination directory, where are files will be copied to
          remote_path: /var/www/redbull.esportssummit-me.com/public
          # Will delete all files in the remote path before uploading
          delete_remote_files: true
          # SFTP args
          sftpArgs: "-o ConnectTimeout=5"